# Services
services:
  # Server service
  server:
    build:
      context: ./CellularAutomatorBackend
      dockerfile: Dockerfile
    container_name: CellularAutomatorBackend
    ports:
      - "8080:8080"
    env_file: ./CellularAutomatorBackend/.env
    #environment:
    #  - MONGO_URL=$MONGO_URL
    #depends_on:
    #  - mongodb

  # Client service
  client:
    build:
      context: ./CellularAutomatorFrontend
      dockerfile: Dockerfile

    container_name: CellularAutomatorFrontend
    ports:
      - "5173:5173"
    depends_on:
      - server

  # Database service
#  mongodb:
#    image: mongo:latest
#    container_name: mongodb_server

#    env_file: ./.env
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
#      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

#    ports:
#      - "27017:27017"

#    volumes:
#      - ./../mydata:/data/db

# Volumes define
#volumes: 
#  mydata: